corrections

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -4,6 +4,7 @@
 if [ $# -lt 4 ]; then
     # If fewer than 4 arguments are provided, display usage instructions
     echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1  # Exit with status 1 to indicate an error
 else
     # If at least 4 arguments are provided, proceed with file transfer using scp
 
@@ -14,4 +15,13 @@ else
     # "$3@$2": Destination in the format USERNAME@IP
     # ":~": Destination directory (user's home directory)
     scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
+    
+    # Check if the scp command was successful
+    if [ $? -eq 0 ]; then
+        echo "File transfer successful."
+        exit 0  # Exit with status 0 to indicate success
+    else
+        echo "File transfer failed."
+        exit 2  # Exit with a custom status (e.g., 2) to indicate failure
+    fi
 fi
